services:
  api:
    build: .
    image: pdf-merge
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    logging:
        driver: json-file
        options:
          max-size: "10m"
          max-file: "3"